"""
YOLOv11n Captcha Training Script for Google Colab
==================================================

Run this in Google Colab with GPU (Runtime → Change runtime type → T4 GPU).
This fine-tunes YOLOv11n on hCaptcha screenshots to detect drag objects (spaceship, star, vial, slot, etc.)

Prerequisites:
1. Collect ~100-500 hCaptcha iframe screenshots
2. Label them using Roboflow or LabelImg
3. Export in YOLO format with a single class: "drag_object"
4. Upload the dataset to Google Drive or GitHub

Usage in Colab:
    !pip install ultralytics
    !wget -O train_colab.py https://your-server/train_colab.py
    !python train_colab.py
"""

import os
import sys
import zipfile
from pathlib import Path

# ─── Configuration ────────────────────────────────────────

# Dataset location - change this to your dataset path
# Format: YOLO format (images/ + labels/ with .txt files)
DATASET_ZIP = "hcaptcha_dataset.zip"  # Or path to your dataset
DATASET_DIR = "hcaptcha_dataset"
MODEL_TYPE = "yolo11n.pt"  # Nano - fastest (~56ms CPU). Try yolo11s.pt for better accuracy
EPOCHS = 100
IMG_SIZE = 640
BATCH_SIZE = 16
CLASSES = ["drag_object", "target_object"]  # Adjust to your classes


def setup_colab():
    """Mount Google Drive and install dependencies."""
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        print("✓ Google Drive mounted")
    except ImportError:
        print("Not in Colab, using local files")
    
    # Install ultralytics
    os.system("pip install -q ultralytics")
    print("✓ Ultralytics installed")


def prepare_dataset():
    """Extract and organize the dataset for YOLO training."""
    if os.path.exists(DATASET_DIR):
        print(f"✓ Dataset directory exists: {DATASET_DIR}")
        return True
    
    # Try to find the dataset
    possible_paths = [
        DATASET_ZIP,
        "/content/drive/MyDrive/" + DATASET_ZIP,
        "/content/drive/MyDrive/hcaptcha/" + DATASET_ZIP,
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            print(f"Extracting {path}...")
            with zipfile.ZipFile(path, 'r') as zf:
                zf.extractall(DATASET_DIR)
            print(f"✓ Dataset extracted to {DATASET_DIR}")
            return True
    
    print("✗ Dataset not found!")
    print(f"  Please upload {DATASET_ZIP} to Colab or Google Drive")
    print("\n  To create a dataset:")
    print("  1. Collect hCaptcha iframe screenshots from your automation")
    print("  2. Label them using https://roboflow.com (free account)")
    print("  3. Export in YOLOv11 format")
    print("  4. Upload the zip to Colab or Google Drive")
    return False


def create_data_yaml():
    """Create the data.yaml configuration file for YOLO training."""
    classes_str = "\n".join(f"  {i}: {name}" for i, name in enumerate(CLASSES))
    
    yaml_content = f"""
# Ultralytics YOLO dataset config for hCaptcha object detection
# Auto-generated by train_colab.py

path: {DATASET_DIR}
train: train/images
val: valid/images

nc: {len(CLASSES)}
names:
{classes_str}
"""
    with open("data.yaml", "w") as f:
        f.write(yaml_content.strip())
    print(f"✓ Created data.yaml with {len(CLASSES)} classes: {CLASSES}")


def train():
    """Train YOLOv11n on the captcha dataset."""
    from ultralytics import YOLO
    
    print(f"\n{'='*60}")
    print(f"  Training {MODEL_TYPE} on captcha dataset")
    print(f"  Epochs: {EPOCHS}, Image size: {IMG_SIZE}, Batch: {BATCH_SIZE}")
    print(f"  Classes: {CLASSES}")
    print(f"{'='*60}\n")
    
    # Load pre-trained model
    print(f"Loading {MODEL_TYPE}...")
    model = YOLO(MODEL_TYPE)
    
    # Train
    print("Starting training...")
    results = model.train(
        data="data.yaml",
        epochs=EPOCHS,
        imgsz=IMG_SIZE,
        batch=BATCH_SIZE,
        device=0,  # Use first GPU (Colab T4)
        patience=20,  # Early stopping
        save=True,
        project="captcha_yolo",
        name="hcaptcha",
        exist_ok=True,
        pretrained=True,
        optimizer="auto",
        cos_lr=True,
        augment=True,
        erasing=0.4,  # Random erasing for robustness
        hsv_h=0.015,  # Color augmentation
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=0.0,  # No rotation (captcha is always upright)
        translate=0.1,
        scale=0.5,
        shear=0.0,
        flipud=0.0,  # No vertical flip (captcha is always upright)
        fliplr=0.5,  # Horizontal flip is fine
        mosaic=1.0,  # Mosaic augmentation for better detection
        mixup=0.1,
    )
    
    print("\n✓ Training complete!")
    print(f"  Best model: {results.save_dir}/weights/best.pt")
    
    # Export to ONNX for Railway deployment
    print("\nExporting to ONNX for fast CPU inference...")
    best_model = YOLO(f"{results.save_dir}/weights/best.pt")
    best_model.export(format="onnx", imgsz=IMG_SIZE, nms=True)
    
    print("\n✓ ONNX model exported!")
    print("  Copy the .onnx file to your Railway project's _models/ directory")
    print("  Then the vision_ai module will use it automatically")


def export_to_onnx():
    """Export the best trained model to ONNX format."""
    from ultralytics import YOLO
    
    # Find the best trained model
    best_path = Path("captcha_yolo/hcaptcha/weights/best.pt")
    if not best_path.exists():
        print(f"✗ Best model not found at {best_path}")
        return
    
    print("Exporting best model to ONNX...")
    model = YOLO(str(best_path))
    model.export(format="onnx", imgsz=IMG_SIZE, nms=True)
    
    # Copy to railay-compatible location
    import shutil
    onnx_file = Path("captcha_yolo/hcaptcha/weights/best.onnx")
    if onnx_file.exists():
        shutil.copy(onnx_file, "_models/yolo11n.onnx")
        print("✓ ONNX model copied to _models/yolo11n.onnx")
        print("  Commit and push this file to update the model on Railway")


if __name__ == "__main__":
    print("=" * 60)
    print("  YOLOv11n Captcha Training Script")
    print("  For Google Colab with GPU")
    print("=" * 60)
    
    setup_colab()
    
    if not prepare_dataset():
        print("\nNo dataset found. Run with --demo to create a sample dataset.")
        if "--demo" in sys.argv:
            print("\nCreating demo dataset for testing...")
            # TODO: Create a sample dataset with synthetic captcha images
        sys.exit(1)
    
    create_data_yaml()
    train()
    export_to_onnx()
    
    print("\n" + "=" * 60)
    print("  Training complete!")
    print("  Next steps:")
    print("  1. Copy the ONNX model to your Railway project")
    print("  2. Push to GitHub")
    print("  3. Railway automatically deploys with the new model")
    print("=" * 60)
