"""Export a fine-tuned LoRA adapter to GGUF and generate an Ollama Modelfile."""

from __future__ import annotations

import shutil
from pathlib import Path

from pipeline.config import TrainingConfig

# ---------------------------------------------------------------------------
# Modelfile templates
# ---------------------------------------------------------------------------


CHATML_MODELFILE = """# Ollama Modelfile — generated by the fine-tuning pipeline
FROM ./{gguf_filename}

TEMPLATE \"\"\"{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
{{ .Response }}<|im_end|>\"\"\"

PARAMETER stop "<|im_end|>"
PARAMETER temperature 0.3
PARAMETER top_p 0.9
PARAMETER num_ctx {num_ctx}
"""

LLAMA3_MODELFILE = """# Ollama Modelfile — generated by the fine-tuning pipeline
FROM ./{gguf_filename}

TEMPLATE \"\"\"{{ if .System }}<|begin_of_text|><|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>\"\"\"

PARAMETER stop "<|eot_id|>"
PARAMETER stop "<|begin_of_text|>"
PARAMETER temperature 0.3
PARAMETER top_p 0.9
PARAMETER num_ctx {num_ctx}
"""


def run_export(config: TrainingConfig) -> Path:
    """Convert the fine-tuned adapter to a GGUF file and write a Modelfile.

    Returns the path to the GGUF file.
    """
    adapter_dir = Path(config.output_dir) / "lora-adapter"
    if not adapter_dir.exists():
        raise FileNotFoundError(
            f"Adapter not found at {adapter_dir}. Run training first."
        )

    print(f"[export] loading base model {config.hf_model_id} …")
    from unsloth import FastLanguageModel

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=config.hf_model_id,
        max_seq_length=config.max_seq_length,
        load_in_4bit=config.load_in_4bit,
        dtype=None,
    )

    # Load LoRA adapter
    from peft import PeftModel

    model = PeftModel.from_pretrained(model, str(adapter_dir))

    # Save as GGUF via Unsloth's native exporter
    gguf_dir = Path(config.output_dir) / "gguf"
    gguf_dir.mkdir(parents=True, exist_ok=True)

    model_name = config.ollama_model_name
    print(f"[export] saving GGUF (quant={config.quantization}) → {gguf_dir} …")
    model.save_pretrained_gguf(
        str(gguf_dir / model_name),
        tokenizer,
        quantization_method=config.quantization,
    )

    # Unsloth names the file <name>-<quant>.gguf
    gguf_filename = f"{model_name}-{config.quantization.upper()}.gguf"
    gguf_path = gguf_dir / gguf_filename

    # Sometimes Unsloth saves without the quant suffix — try to find it
    if not gguf_path.exists():
        candidates = list(gguf_dir.glob("*.gguf"))
        if len(candidates) == 1:
            gguf_path = candidates[0]
            gguf_filename = gguf_path.name
        elif not candidates:
            raise FileNotFoundError(f"No GGUF file found in {gguf_dir}")

    print(f"[export] GGUF saved → {gguf_path}  ({gguf_path.stat().st_size / 1e9:.2f} GB)")

    # ---------- Modelfile ----------
    template = config.chat_template
    modelfile_content = (
        LLAMA3_MODELFILE if template == "llama3" else CHATML_MODELFILE
    ).format(gguf_filename=gguf_filename, num_ctx=config.max_seq_length)

    modelfile_path = gguf_dir / "Modelfile"
    modelfile_path.write_text(modelfile_content)
    print(f"[export] Modelfile saved → {modelfile_path}")

    # ---------- convenience copy ----------
    # Copy the GGUF + Modelfile to a flat "ollama-model" dir for easy `ollama create`
    ollama_dir = Path(config.output_dir) / "ollama-model"
    if ollama_dir.exists():
        shutil.rmtree(ollama_dir)
    ollama_dir.mkdir()
    shutil.copy2(gguf_path, ollama_dir / gguf_filename)
    shutil.copy2(modelfile_path, ollama_dir / "Modelfile")
    print(f"[export] ollama-ready dir → {ollama_dir}/")

    print(f"\n{'=' * 60}")
    print(f"  To register with Ollama:")
    print(f"  cd {ollama_dir}")
    print(f"  ollama create {model_name} -f Modelfile")
    print(f"  ollama run {model_name}")
    print(f"{'=' * 60}\n")

    return gguf_path
